### ISSUE TITLE
How to? 

### ISSUE THREAD

**Issue by Dershowitz011** [tihmstar/libipatcher#1]
Can you please tell me how to dompile? Slightky detalied instructions please. Thank you.

**Comment by Dershowitz011** [comment]
Sir please reply soon before Apple stops signing. Please sir.

**Comment by 2Klasic** [comment]
A detailed guide will be posted on twitter within the next 2 days...please follow either myself @2klasic or @alitek123 on twitter for more information

**Comment by Dershowitz011** [comment]
Done sir. ASAP sir. Before Apple stops signing iOS 10.3.2. Thank you. 😇
