### ISSUE TITLE
ld: library not found for -lcommon

### ISSUE THREAD

**Issue by rA9stuff** [tihmstar/libipatcher#14]
I've copied the library files from xpwn to `/usr/local/include` but it still can't find the required library
![Screen Shot 2019-11-17 at 19 35 21](https://user-images.githubusercontent.com/38068746/69010492-6c3b4700-0971-11ea-92da-e5dcc08b5812.png)

**Comment by Halo-Michael** [comment]
Damn, how do you fix that?
![B42F6334-AB98-42C1-84C2-AEA080C7635C](https://user-images.githubusercontent.com/45062120/69133266-9a936080-0af0-11ea-8d4f-047cd5233619.png)

**Comment by Haifisch** [comment]
I presume you've both compiled and installed [xpwn](https://github.com/planetbeing/xpwn) but are simply missing the library in the 'common/' subdirectory.

**Comment by Merculous** [comment]
Try this out! https://github.com/Merculous/xpwn Just run ./install.sh (make sure cmake is downloaded from brew). I hope my findings will help you build the needed files.

This will enable you to also build for Odysseus support in futurerestore, both 32 and 64 bit, if liboffsetfinder64 was compiled.

**Comment by tihmstar** [comment]
libipatcher not features pre-built binaries, see releases section.
If you wanna see how these are compiled, check https://github.com/tihmstar/libipatcher/blob/master/.github/workflows/main.yml
