### ISSUE TITLE
fatal error: 'xpwn/libxpwn.h' file not found

### ISSUE THREAD

**Issue by tolikes** [tihmstar/libipatcher#18]
#include <xpwn/libxpwn.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [libipatcher_la-libipatcher.lo] Error 1
make: *** [install-recursive] Error 1

**Comment by Merculous** [comment]
Copy the include files from an xpwn repo to /usr/local/include, that'll fix it.

**Comment by tihmstar** [comment]
No londer relevant/needed
