### ISSUE TITLE
iOS 10 not supported?

### ISSUE THREAD

**Issue by iApeiron** [tihmstar/libipatcher#2]
The only iOS 10 keys currently available are 10.0b1 keys for the iPhone5,*.
I layed out all of the keys for iPhone5,2 into a file based on the others in icj's API (and loaded it onto a local XAMPP server), file linked below:
http://www.mediafire.com/file/yyaqcv98159v09u/14A5261v
When I run the compiled futurerestore against it, it says keys are not available.
When I copy an existing example from the API, it works, so I know my setup is working correctly. 
Below is the necessary ipsw for testing 10.0b1:
http://www.mediafire.com/file/z7oj9a0r5dl492z/iPhone_4.0_32bit_10.0_14A5261v_Restore.ipsw

Thank you, Tihmstar, for the great work! All my other tests have successed!

**Comment by tihmstar** [comment]
i'm not quite sure what exactly you are doing, but this sound like an issue with your setup.
If it says keys not found, then it simply can't find the keys lol
