### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type libipatcher::exception std::exception

### ISSUE THREAD

**Issue by iFred09** [tihmstar/libipatcher#3]
![image](https://user-images.githubusercontent.com/22419166/27242986-09dbbb34-52e0-11e7-978e-8cd2576c11db.jpg)

Hey,

I have this problem when i try to restore my iPad 4 jailbroken to iOS 6.1.3 or 8.4 with the futurerestore / libipatcher method but it don’t work. When it try to send RestoreLogo, i have this error.

It’s possible to fix this ? I’m on OS X El Capitan 10.11.5 and i have Xcode installed too.

Futurerestore v140
libipatcher v27

**Comment by tihmstar** [comment]
So according to your screenshot you're trying to restore iPad3,4 to iOS 6.1.3.
If you check https://firmware-keys.ipsw.me/firmware/iPad3,4/10B329 you can see, that iBSS and IBEC keys are on @cj123's api, but AppleLogo keys are missing ("TODO").
You can ask him nicely to put the firmware keys there so libipatcher can fetch them

**Comment by cj123** [comment]
I think this exception really should be caught and or dealt with in such a way that explains what's going on - i'd imagine many people will run into this issue. I've not yet looked into TODOs in my database (mostly because I forgot they exist).

**Comment by tihmstar** [comment]
added userfriendly errormsg in 9cb0b24db3ecdf07b2a5b210791ae116385d848f

**Comment by 0neday** [comment]
@tihmstar  I compare [this](https://firmware-keys.ipsw.me/firmware/iPhone4,1/12B440) and [iphone key wiki ](https://www.theiphonewiki.com/wiki/SUOkemoTaosTwo_12B466_(iPhone4,1)), and find the key and iv is error
