### ISSUE TITLE
"library not found for -lcommon" while compiling libipatcher

### ISSUE THREAD

**Issue by jihyo-song** [tihmstar/libipatcher#5]
![capture](https://user-images.githubusercontent.com/28991651/27325159-b6528156-55d1-11e7-87da-98ce392f2483.PNG)
am i missing some dependency so that problem happen ? always stuck at "library not found for -lcommon". im using xpwn from [here](https://github.com/planetbeing/xpwn), then i copy all file from xpwn/includes to libipatcher/include, but still that problem happen again. am i doing wrong step or what ? ty.

**Comment by 1isten** [comment]
Did you solve this issue?

**Comment by 0neday** [comment]
copy library files from xpwn to /usr/local/include
